//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagene
    {
        public int id_image { get; set; }
        public string ruta { get; set; }
        public Nullable<int> id_visita { get; set; }
    
        public virtual Visita Visita { get; set; }
    }
}
