//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Visita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visita()
        {
            this.Facturas = new HashSet<Factura>();
            this.Imagenes = new HashSet<Imagene>();
        }
        
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Costo { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        [Display(Name = "Longitud")]
        public Nullable<decimal> Altitud { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Tecnologia { get; set; }
        public Nullable<int> Tipo { get; set; }
        [Display(Name = "Estado de Pago")]
        public string EstatusPago { get; set; }
        [Display(Name = "Estado de Cobro")]
        public string EstatusCobro { get; set; }
        public Nullable<System.DateTime> FechaMaxima { get; set; }
        public int Folio { get; set; }
        public Nullable<int> Ingeniero { get; set; }
        public string EstadoVisita { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Estado Estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagene> Imagenes { get; set; }
        public virtual Ingeniero Ingeniero1 { get; set; }
        public virtual Tecnologia Tecnologia1 { get; set; }
        public virtual TipoVisita TipoVisita { get; set; }
    }
}
