//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen()
        {
            this.equipo_unico = new HashSet<equipo_unico>();
        }
    
        public int id_Almacen { get; set; }
        [Display(Name ="Longitud")]
        public Nullable<decimal> Altitud { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        [Display(Name = "Ingeniero")]
        public Nullable<int> Ing { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> codigo_postal { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual Ingeniero Ingeniero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipo_unico> equipo_unico { get; set; }
    }
}
