//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo_unico
    {
        public string no_serie { get; set; }
        public Nullable<int> no_almacen { get; set; }
        public string modelo { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual equipo_generico equipo_generico { get; set; }
    }
}
