//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities2 : DbContext
    {
        public ERPEntities2()
            : base("name=ERPEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Almacen> Almacens { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<equipo_generico> equipo_generico { get; set; }
        public virtual DbSet<equipo_unico> equipo_unico { get; set; }
        public virtual DbSet<Estado> Estadoes { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Imagene> Imagenes { get; set; }
        public virtual DbSet<Ingeniero> Ingenieroes { get; set; }
        public virtual DbSet<Tecnologia> Tecnologias { get; set; }
        public virtual DbSet<TipoVisita> TipoVisitas { get; set; }
        public virtual DbSet<Visita> Visitas { get; set; }
    }
}
